submenu:
  - name: Reaching Liverpool
    relative_url: /local
  - name: Accommodation
    relative_url: /local/accommodation
  - name: Venues
    relative_url: /local/venues
  - name: Social Activities
    relative_url: /local/social
  - name: Code of Conduct
    relative_url: /local/code-of-conduct
