name: Scheduled Sync

on:
  schedule:
    - cron: '*/15 * * * *' # every 15 minutes
  workflow_dispatch:       # also allow manual runs

jobs:
  sync-workshops:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Update submodules
      run: |
        git submodule update --remote --merge --force
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add workshops
        git commit -m "Auto-update workshops from repo-2" || echo "No changes to commit"
        git push
